//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP2_JewelryApp_05092016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public int CollectionID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public decimal Cost { get; set; }
        public string StyleNum { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Retired { get; set; }
        public bool Own { get; set; }
    
        public virtual Collection Collection { get; set; }
    }
}
